name: flutter_opendroneid
description: A flutter plugin for reading Wi-Fi and Bluetooth Remote ID advertisements using native Android and iOS platform-specific implementation.
version: 0.9.4
repository: https://github.com/dronetag/flutter-opendroneid

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  pigeon: ^3.2.7

flutter:
  plugin:
    platforms:
      android:
        package: cz.dronetag.flutter_opendroneid
        pluginClass: FlutterOpendroneidPlugin
      ios:
        pluginClass: FlutterOpendroneidPlugin